#!/usr/bin/env python

#
# XXX detect duplicated words and phrases and show compile error
#
import os
import sys

rhyme_file_paths = [x for x in sys.argv[1:] if os.path.exists(x)]

basic_particles = ["is", "are", "were", "had", "has", "it's", "it", "there", "yes", "yo"]

def compile_rhyme(rhyme_file):
    f = open(rhyme_file, "r")
    contents = f.read()
    f.close()

    word_dict = {}
    for word in contents.replace("\n", " ").split(' '):
        if word in word_dict:
            word_dict[word] += 1
        else:
            word_dict[word] = 1 

    print("\n[duplications]")
    for word, count in word_dict.items():
        if(count > 1) and not (word in basic_particles):
            print("%s: %s" % (word, count))
    print
  
for rhyme_file in rhyme_file_paths:
    compile_rhyme(rhyme_file)
